"""Scene order for the full video: (file stem in scenes/, Scene class, chapter title)."""
SCENES = [
    ("s00_intro", "Intro", "Prologue"),
    ("s01_bdh", "BDHModel", "1. The Dragon Hatchling"),
    ("s02_task", "BindingTask", "2. Context-conditional binding"),
    ("s03_channels", "ChannelsAndGate", "3. Channels and a gate"),
    ("s04_flat_start", "FlatStart", "4. A flat start"),
    ("s05_rig", "ConvAndMuon", "5. Two more parts"),
    ("s06_scoring", "Scoring", "6. How a run is scored"),
    ("s07_history", "History", "7. Phases I to IV"),
    ("s08_method", "Method", "8. How the work is checked"),
    ("s09_repo", "RepoTour", "9. Inside the repository"),
    ("s10_four_streams", "FourStreams", "10. Phase V: four streams"),
    ("s11_curriculum", "StreamCurriculum", "11. Eight streams by curriculum"),
    ("s12_screens", "Screens", "12. The race"),
    ("s13_recipe", "Recipe", "13. The recipe"),
    ("s14_slow_start", "SlowStart", "14. Slow memory and a hinge, confirmed"),
    ("s15_recipe_scope", "RecipeScope", "15. Which part matters"),
    ("s16_kick", "EarlyKick", "16. The hinge is an early kick"),
    ("s17_early_recipe", "EarlyRecipeTest", "17. The early-recipe test"),
    ("s18_merges", "Merges", "18. Breaking merges"),
    ("s19_eight_streams", "EightStreams", "19. The gate forgets the context"),
    ("s20_distant_cues", "DistantCues", "20. Distant cues"),
    ("s21_standing", "WhereItStands", "21. Where the mechanism stands"),
    ("s22_retrospective", "Retrospective", "22. Keeping score on itself"),
    ("s23_outlook", "Outlook", "23. Limits and next steps"),
]
